In [2]:
import numpy as np

### 1. 넘파이를 사용하여 다음과 같은 행렬을 만들고, 이 배열에서 값 70을 인덱싱하세요.  (3.1 - 연습문제 1 변형)
10 20 30 40 <br>
50 60 70 80 <br>

In [3]:
# 밑에 코드 작성
arr1 = np.array([[10,20,30,40],[50,60,70,80]])
print(arr1[1,2], arr1[1][2])

70 70


### 2. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라. (연습문제 3.3.2)

In [28]:
v = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

# 밑에 코드 작성
eng_rank = np.argsort(v[1])
eng_rank
v[:,[0,3,1,2]]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

### 3. 코사인 유사도 함수 구현하기

In [32]:
%%time
def cos_sim(A,B):
    # 밑에 코드 작성
    return np.dot(A,B) / (np.linalg.norm(A) * np.linalg.norm(B))

# Test
doc1 = np.array([0,1,1,1,1,1,1,1,1])
doc2 = np.array([1,0,1,1,1,1,1,1,1])
result = round(cos_sim(doc1, doc2),2)
result

CPU times: total: 0 ns
Wall time: 997 µs


0.87

In [32]:
# Test
doc1 = np.array([0,1,1,1])
doc2 = np.array([1,0,1,1])
result = round(cos_sim(doc1, doc2),2)
result

0.67

- 정답 : 0.67

## 4,5번 문제 : 붓꽃 데이터 활용 

### 4. 붓꽃들의 변수별 가중치를 통해 전체 붓꽃 가중평균 구하기

- 변수별 가중치
    - 꽃받침의 길이 : 0.3, 꽃받침의 폭 : 0.2, 꽃잎의 길이 : 0.25, 꽃잎의 폭 : 0.25

In [33]:
from sklearn.datasets import load_iris

iris = load_iris() # 붓꽃 데이터 로드
X = iris.data

def weighted_average(data):
    
    # 밑에 코드 작성
    weight = [0.3,0.2,0.25,0.25]
    return np.dot(data, weight).mean()

result = weighted_average(X)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

- 정답 <br>
3.6038

In [36]:
def weighted_average(data):
    # 변수별 가중치 정의
    weights = np.array([0.3, 0.2, 0.25, 0.25])
    
    # 가중평균 계산
    weighted_avg = np.dot(data, weights)
    
    return np.round(weighted_avg, 4)

result = weighted_average(X)
print(result)

[2.63  2.47  2.425 2.425 2.62  2.925 2.485 2.605 2.3   2.49  2.785 2.57
 2.415 2.19  2.89  3.065 2.825 2.655 2.97  2.74  2.775 2.745 2.4   2.74
 2.645 2.55  2.68  2.685 2.64  2.5   2.51  2.775 2.78  2.89  2.515 2.49
 2.725 2.565 2.295 2.635 2.6   2.21  2.335 2.75  2.865 2.465 2.74  2.42
 2.755 2.56  4.265 4.06  4.29  3.435 4.035 3.72  4.125 3.025 4.035 3.425
 3.025 3.795 3.49  3.935 3.485 4.08  3.78  3.555 3.8   3.43  4.06  3.715
 3.99  3.865 3.9   4.03  4.15  4.285 3.88  3.355 3.355 3.305 3.555 4.015
 3.72  4.005 4.18  3.775 3.63  3.475 3.57  3.93  3.56  3.035 3.595 3.66
 3.665 3.84  3.055 3.62  4.675 4.03  4.73  4.32  4.55  5.055 3.52  4.795
 4.41  5.03  4.365 4.26  4.54  3.96  4.175 4.46  4.375 5.295 5.13  3.865
 4.71  3.965 5.045 4.105 4.62  4.75  4.07  4.105 4.405 4.61  4.78  5.23
 4.43  4.1   4.1   5.01  4.57  4.365 4.05  4.565 4.63  4.54  4.03  4.73
 4.72  4.485 4.115 4.35  4.465 4.095]


### 5. 붓꽃들의 각 변수별 기술통계량 구하기 : 평균, 중앙값, 표준편차

- 소수점 둘째자리까지
- 2차원 리스트의 형태로 반환
    - [[변수 1의 평균, 변수 1의 중앙값, 변수 1의 표준편차], ..., [변수 4의 평균, 변수 4의 중앙값, 변수 4의 표준편차]]

In [60]:
def stats(X):

    # 밑에 코드 작성
    stats = np.column_stack((
        np.mean(X, axis=0), np.median(X, axis=0), np.std(X, axis=0)
    ))

    stats = np.round(stats, 2)
    return stats

result = stats(X)
result



array([[5.84, 5.8 , 0.83],
       [3.06, 3.  , 0.43],
       [3.76, 4.35, 1.76],
       [1.2 , 1.3 , 0.76]])

In [37]:
np.mean(X, axis=1), np.median(X, axis=1), np.std(X, axis=1)

(array([2.55 , 2.375, 2.35 , 2.35 , 2.55 , 2.85 , 2.425, 2.525, 2.225,
        2.4  , 2.7  , 2.5  , 2.325, 2.125, 2.8  , 3.   , 2.75 , 2.575,
        2.875, 2.675, 2.675, 2.675, 2.35 , 2.65 , 2.575, 2.45 , 2.6  ,
        2.6  , 2.55 , 2.425, 2.425, 2.675, 2.725, 2.825, 2.425, 2.4  ,
        2.625, 2.5  , 2.225, 2.55 , 2.525, 2.1  , 2.275, 2.675, 2.8  ,
        2.375, 2.675, 2.35 , 2.675, 2.475, 4.075, 3.9  , 4.1  , 3.275,
        3.85 , 3.575, 3.975, 2.9  , 3.85 , 3.3  , 2.875, 3.65 , 3.3  ,
        3.775, 3.35 , 3.9  , 3.65 , 3.4  , 3.6  , 3.275, 3.925, 3.55 ,
        3.8  , 3.7  , 3.725, 3.85 , 3.95 , 4.1  , 3.725, 3.2  , 3.2  ,
        3.15 , 3.4  , 3.85 , 3.6  , 3.875, 4.   , 3.575, 3.5  , 3.325,
        3.425, 3.775, 3.4  , 2.9  , 3.45 , 3.525, 3.525, 3.675, 2.925,
        3.475, 4.525, 3.875, 4.525, 4.15 , 4.375, 4.825, 3.4  , 4.575,
        4.2  , 4.85 , 4.2  , 4.075, 4.35 , 3.8  , 4.025, 4.3  , 4.2  ,
        5.1  , 4.875, 3.675, 4.525, 3.825, 4.8  , 3.925, 4.45 , 4.55 ,
      

In [51]:
def stats(X):
    result = []
    X = X.T
    for v in X:
        print(v)
        mean_value = np.mean(v)
        median_value = np.median(v)
        std_value = np.std(v)
        
        result.append([round(mean_value, 2), round(median_value, 2), round(std_value, 2)])
    
    return result

In [52]:
stats(X)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2

[[5.84, 5.8, 0.83], [3.06, 3.0, 0.43], [3.76, 4.35, 1.76], [1.2, 1.3, 0.76]]

In [44]:
for v in X.T:
    print(np.mean(v))

5.843333333333334
3.0573333333333337
3.7580000000000005
1.1993333333333336


- 정답 <br>
[[5.84, 5.8, 0.83], [3.06, 3.0, 0.43], [3.76, 4.35, 1.76], [1.2, 1.3, 0.76]]

- numpy 공홈 : https://numpy.org/
- numpy ex100 : https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

In [13]:
R = np.random.randn(250)
stock = []
for i in range(250):
    price = 10000
    print((R[i] / 100 + 1) * price)
    stock.append(price)

print(stock)

10144.877607907605
9665.222842149766
10031.689107889226
10010.010977105605
9944.210456432174
9870.483349917173
10076.869014291793
10100.698877401148
10069.069457550859
9899.206317955124
9898.040720926974
9982.092277332988
10085.573101115064
9971.395056618236
9922.679812744345
10159.850501249179
10025.861043994117
9925.964174296401
9944.559853542258
10095.644342860905
9803.517229544033
9886.968721203497
10075.710501064723
10218.601428315616
9970.937544867395
9903.172341596037
10034.800996378392
10088.575753829931
9994.340345824017
10064.501499783299
10098.487299119044
10139.106276165196
10008.218997072303
10240.896675910259
9844.437506068518
9923.368139526867
10145.089755678362
9980.000828952614
9990.558688202116
9824.247839602987
9959.385134293663
10123.57192258877
9807.230533828044
9984.659306650257
9894.354258870222
10087.723376819644
10000.140341712631
10052.382731040716
10169.37259667189
9911.602761377288
9942.708294077884
9930.990140498483
9951.624250387047
10130.194907962537
1001

In [30]:
n = 10000
x = np.random.randn(250)
for i in x:
    n = n * (1 + (i / 100))
    print("{:,}원".format(round(n)))

9,865원
9,887원
10,005원
9,908원
9,903원
9,925원
9,970원
9,926원
10,042원
9,905원
10,003원
9,901원
9,943원
10,063원
9,896원
9,894원
9,667원
9,636원
9,632원
9,535원
9,421원
9,245원
9,313원
9,261원
9,400원
9,233원
9,056원
9,101원
9,218원
9,127원
9,031원
9,041원
8,846원
8,705원
8,828원
8,944원
8,920원
8,964원
8,883원
8,984원
9,102원
9,214원
9,157원
9,003원
9,010원
8,917원
8,958원
9,080원
8,950원
9,103원
9,050원
9,153원
9,172원
9,254원
9,088원
9,042원
9,001원
8,899원
8,976원
9,023원
9,005원
9,097원
9,207원
9,328원
9,240원
9,216원
8,960원
8,856원
8,882원
8,911원
8,927원
8,949원
8,784원
8,732원
8,760원
8,699원
8,685원
8,707원
8,810원
8,790원
8,817원
8,842원
8,658원
8,707원
8,634원
8,563원
8,800원
8,746원
8,662원
8,558원
8,593원
8,433원
8,409원
8,362원
8,299원
8,258원
8,442원
8,381원
8,402원
8,435원
8,418원
8,423원
8,450원
8,475원
8,495원
8,572원
8,525원
8,317원
8,362원
8,511원
8,500원
8,686원
8,660원
8,619원
8,520원
8,564원
8,561원
8,548원
8,497원
8,439원
8,497원
8,450원
8,403원
8,354원
8,302원
8,157원
8,072원
8,136원
8,190원
8,225원
8,033원
8,027원
8,009원
7,972원
8,008원
8,087원
8,164원
8,119원
8,066원
8,119원
8,122원
8,203원
8,