In [1]:
import numpy as np

## 1차원 배열, 벡터화 연산

In [5]:
ar = np.array([10,11,12,13])

print(ar*2)
print(ar * ar)
print(ar % 2 == 0)

[20 22 24 26]
[100 121 144 169]
[ True False  True False]


In [12]:
print(f"배열의 차원은 {ar.ndim}")
print(f"배열의 형태는 {ar.shape}")

배열의 차원은 1
배열의 형태는 (4,)


## 2차원 배열 - 슬라이싱, 인덱싱

In [23]:
mat = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(mat)
print(mat[1,1])
print(mat[-1,-2])
print(mat[:,2])
print(mat[mat % 2 == 0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5
10
[ 2  6 10]
[ 0  2  4  6  8 10]


In [24]:
print(f"배열의 차원은 {mat.ndim}")
print(f"배열의 형태는 {mat.shape}")
print(mat.dtype)

배열의 차원은 2
배열의 형태는 (3, 4)
int32


## 배열의 변형

In [34]:
print(np.ones((2,3)))
print(np.arange(5,15))
print(np.linspace(0,100,9))

[[1. 1. 1.]
 [1. 1. 1.]]
[ 5  6  7  8  9 10 11 12 13 14]
[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]


In [46]:
a = np.arange(10)
print(a.reshape(2,5))
print(a.reshape(5,-1))
print(a.flatten())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [54]:
b = np.ones(10)
print(np.hstack([a,b]))
print(np.vstack([a,b]))
print(np.dstack([a,b]))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[[0. 1.]
  [1. 1.]
  [2. 1.]
  [3. 1.]
  [4. 1.]
  [5. 1.]
  [6. 1.]
  [7. 1.]
  [8. 1.]
  [9. 1.]]]


## 배열의 연산

In [70]:
%%time
a = np.arange(5)
b = np.arange(5,10)
print(a + b)
print(a - 1)

[ 5  7  9 11 13]
[-1  0  1  2  3]
CPU times: total: 15.6 ms
Wall time: 1.99 ms


## 정렬

In [75]:
matrix = np.array(
    [
        [23,13,15,51],[21,33,23,31], [42,12,43,32]
    ]
)
print(np.sort(matrix))
print(np.sort(matrix, axis=0))
print(np.argsort(matrix))

[[13 15 23 51]
 [21 23 31 33]
 [12 32 42 43]]
[[21 12 15 31]
 [23 13 23 32]
 [42 33 43 51]]
[[1 2 0 3]
 [0 2 3 1]
 [1 3 0 2]]
